<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>32658c1d-8f6b-4a5b-b3b1-daaee2843457</testSuiteGuid>
   <testCaseLink>
      <guid>f41ad409-8358-4940-b07c-f0f2c1a46305</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day2/Test_DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ba0d4722-a731-4411-b0aa-a8ee9a75839a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataForLoginTest</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ba0d4722-a731-4411-b0aa-a8ee9a75839a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9ab8dfe4-95bc-41e2-a9ab-5b4ba7d02468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba0d4722-a731-4411-b0aa-a8ee9a75839a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e9a8efb7-2a85-4799-b1fa-13e21d6b126f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
